id: IA3D8655D
source: https://library.bdrc.io
source_file: null
initial_creation_type: ocr
imported: '2020-03-29T19:23:25+00:00'
last_modified: '2022-06-08T01:55:42.967212+00:00'
parser: https://github.com/OpenPecha-dev/openpecha-toolkit/blob/231bba39dd1ba393320de82d4d08a604aabe80fc/openpecha/formatters/google_orc.py
source_metadata:
  id: bdr:W00EGS1016261
  title: སྟག་ལུང་བཀའ་བརྒྱུད་ཀྱི་བསང་གསོལ་རྒྱས་པ
  author: ''
  access: http://purl.bdrc.io/admindata/AccessOpen
  restrictedInChina: false
  base:
    191D:
      image_group_id: I00JW501138
      title: ''
      total_pages: 604
      order: 1
      base_file: 191D.txt
statistics: {}
quality: {}
copyright:
  status: Unknown
  notice: ''
  info_url: null
license: null
