id: P004558
initial_creation_type: ocr
source_metadata:
  id: bdr:W00EGS1016261
  title: སྟག་ལུང་བཀའ་བརྒྱུད་ཀྱི་བསང་གསོལ་རྒྱས་པ
  author: ''
  volumes:
    635e4cd04bd7479a9f94a23f5297344e:
      image_group_id: I00JW501138
      title: ''
      volume_number: 1
      total_pages: 604
      base_file: v001.txt
